// ══════════════════════════════════════
// 判斷題題庫（110 題，含程式碼找錯）
// ══════════════════════════════════════
const ID_POOL=[
    // ─── 半形英文（10） ───
    {s:'我的 email 是 {M}andy@gmail.com',           m:'a', t:'half',cat:'半形英文'},
    {s:'請在 username 欄填入 {M}user123',            m:'u', t:'half',cat:'半形英文'},
    {s:'The folder is named {M}documents',           m:'d', t:'half',cat:'半形英文'},
    {s:'網址輸入 {M}www.school.edu.tw',              m:'w', t:'half',cat:'半形英文'},
    {s:'Press {M}enter to confirm',                  m:'e', t:'half',cat:'半形英文'},
    {s:'請從 {M}downloads 下載檔案',                 m:'d', t:'half',cat:'半形英文'},
    {s:'用 {M}vscode 編輯程式碼',                    m:'v', t:'half',cat:'半形英文'},
    {s:'在 {M}cmd 中執行指令',                       m:'c', t:'half',cat:'半形英文'},
    {s:'上傳到 {M}github 儲存庫',                    m:'g', t:'half',cat:'半形英文'},
    {s:'安裝 {M}python 套件',                        m:'p', t:'half',cat:'半形英文'},
    // ─── 抬頭大寫（10） ───
    {s:'{M}Taiwan is a beautiful island.',           m:'T', t:'half',cat:'抬頭大寫'},
    {s:'My name is {M}Andy Chen.',                   m:'A', t:'half',cat:'抬頭大寫'},
    {s:'Press {M}Ctrl + C to copy.',                 m:'C', t:'half',cat:'抬頭大寫'},
    {s:'公司名稱是 {M}Best Tech Co.',                m:'B', t:'half',cat:'抬頭大寫'},
    {s:'{M}Windows 是微軟作業系統。',                m:'W', t:'half',cat:'抬頭大寫'},
    {s:'今天是{M}Monday。',                          m:'M', t:'half',cat:'抬頭大寫'},
    {s:'王先生姓 {M}Wang。',                         m:'W', t:'half',cat:'抬頭大寫'},
    {s:'{M}Python 是一種程式語言。',                 m:'P', t:'half',cat:'抬頭大寫'},
    {s:'請閱讀第 {M}Section 5。',                    m:'S', t:'half',cat:'抬頭大寫'},
    {s:'{M}Constitution 是憲法。',                   m:'C', t:'half',cat:'抬頭大寫'},
    // ─── 全形英文（10） ───
    {s:'表單上寫的是 {M}Ａndy，應改為半形',          m:'Ａ',t:'full',cat:'全形英文'},
    {s:'帳號不小心輸入了 {M}ｕser123',               m:'ｕ',t:'full',cat:'全形英文'},
    {s:'密碼誤輸入為 {M}Ｐassword123',               m:'Ｐ',t:'full',cat:'全形英文'},
    {s:'文件中出現了 {M}ｅmail 全形字',              m:'ｅ',t:'full',cat:'全形英文'},
    {s:'報告標題寫成了 {M}Ｔype Lab',                m:'Ｔ',t:'full',cat:'全形英文'},
    {s:'信件開頭寫了 {M}Ｄear Sir',                  m:'Ｄ',t:'full',cat:'全形英文'},
    {s:'稱謂誤用 {M}Ｍr. Wang',                      m:'Ｍ',t:'full',cat:'全形英文'},
    {s:'欄位標題為 {M}Ｎame，應改半形',              m:'Ｎ',t:'full',cat:'全形英文'},
    {s:'註解中有 {M}ＦIXME 未修正',                  m:'Ｆ',t:'full',cat:'全形英文'},
    {s:'網址輸入了 {M}ｗww.google.com',               m:'ｗ',t:'full',cat:'全形英文'},
    // ─── 半形數字（10） ───
    {s:'我的座號是 {M}12 號',                        m:'1', t:'half',cat:'半形數字'},
    {s:'電話 0{M}912-345-678',                      m:'9', t:'half',cat:'半形數字'},
    {s:'port 號為 :{M}8080',                        m:'8', t:'half',cat:'半形數字'},
    {s:'今天氣溫是 {M}25 度',                        m:'2', t:'half',cat:'半形數字'},
    {s:'教室在 {M}3 樓',                             m:'3', t:'half',cat:'半形數字'},
    {s:'IP 位址為 192{M}.168.1.1',                   m:'.', t:'half',cat:'半形數字'},
    {s:'現場來了 {M}50 人',                          m:'5', t:'half',cat:'半形數字'},
    {s:'版本號為 v{M}2.0.1',                        m:'2', t:'half',cat:'半形數字'},
    {s:'目前氣溫 {M}28°C',                          m:'2', t:'half',cat:'半形數字'},
    {s:'地址在 {M}168 號',                          m:'1', t:'half',cat:'半形數字'},
    // ─── 全形數字（10） ───
    {s:'報名表填了 {M}１２ 號',                      m:'１',t:'full',cat:'全形數字'},
    {s:'合約書是 {M}２０２４ 年',                    m:'２',t:'full',cat:'全形數字'},
    {s:'表單金額 {M}５００ 元',                      m:'５',t:'full',cat:'全形數字'},
    {s:'頁碼為 第 {M}３ 頁',                         m:'３',t:'full',cat:'全形數字'},
    {s:'試卷編號 {M}００１',                         m:'０',t:'full',cat:'全形數字'},
    {s:'日期寫成 {M}２０２４-０１',                  m:'２',t:'full',cat:'全形數字'},
    {s:'緊急電話 {M}９９９',                         m:'９',t:'full',cat:'全形數字'},
    {s:'價格為 NT{M}３００ 元',                      m:'３',t:'full',cat:'全形數字'},
    {s:'樓層標示為 B{M}１',                          m:'１',t:'full',cat:'全形數字'},
    {s:'密碼設為 {M}１２３４５６',                    m:'１',t:'full',cat:'全形數字'},
    // ─── 半形符號（10） ───
    {s:'Email: andy{M}@school.edu',                  m:'@', t:'half',cat:'半形符號'},
    {s:'Hello{M}, how are you?',                     m:',', t:'half',cat:'半形符號'},
    {s:'路徑用 {M}/ 分隔',                           m:'/', t:'half',cat:'半形符號'},
    {s:'Shift{M}+1 輸入驚嘆號',                      m:'+', t:'half',cat:'半形符號'},
    {s:'程式碼中 {M}( 開始函數',                     m:'(', t:'half',cat:'半形符號'},
    {s:'備註標示 P{M}.S.',                           m:'.', t:'half',cat:'半形符號'},
    {s:'變數命名用底線 {M}_ 開頭',                    m:'_', t:'half',cat:'半形符號'},
    {s:'折扣為 {M}% 百分比',                         m:'%', t:'half',cat:'半形符號'},
    {s:'條件判斷 {M}>= 表示大於等於',                 m:'>', t:'half',cat:'半形符號'},
    {s:'快速鍵為 Ctrl{M}+Alt+Del',                   m:'+', t:'half',cat:'半形符號'},
    {s:'程式註解用 {M}# 開頭',                       m:'#', t:'half',cat:'半形符號'},
    {s:'變數賦值用 {M}= 符號',                       m:'=', t:'half',cat:'半形符號'},
    {s:'乘法運算用 {M}* 符號',                       m:'*', t:'half',cat:'半形符號'},
    // ─── 全形符號（10） ───
    {s:'你好{M}，我是新同學。',                      m:'，',t:'full',cat:'全形符號'},
    {s:'請問你叫什麼名字{M}？',                      m:'？',t:'full',cat:'全形符號'},
    {s:'路徑誤輸入 C{M}：\\Users',                  m:'：',t:'full',cat:'全形符號'},
    {s:'表單括號輸入成 {M}（姓名）',                 m:'（',t:'full',cat:'全形符號'},
    {s:'中文結尾加了 {M}！',                         m:'！',t:'full',cat:'全形符號'},
    {s:'全形句號寫成 {M}。',                       m:'。',t:'full',cat:'全形符號'},
    {s:'範圍用 {M}～ 表示',                          m:'～',t:'full',cat:'全形符號'},
    {s:'頓號使用 {M}、',                       m:'、',t:'full',cat:'全形符號'},
    {s:'全形分號寫成 {M}；',                         m:'；',t:'full',cat:'全形符號'},
    {s:'全形右括號 {M}）',                           m:'）',t:'full',cat:'全形符號'},
    // ─── 中文標點（10） ───
    {s:'她說{M}：「等一下！」',                      m:'：',t:'full',cat:'中文標點'},
    {s:'句子結尾用 {M}。',               m:'。',t:'full',cat:'中文標點'},
    {s:'全形逗號 {M}，',                     m:'，',t:'full',cat:'中文標點'},
    {s:'這句話結尾是句號{M}。',                      m:'。',t:'full',cat:'中文標點'},
    {s:'清單用{M}、分隔項目',                        m:'、',t:'full',cat:'中文標點'},
    {s:'全形問號 {M}？',                     m:'？',t:'full',cat:'中文標點'},
    {s:'編號方式為{M}（一）（二）',                  m:'（',t:'full',cat:'中文標點'},
    {s:'全形驚嘆號 {M}！',                         m:'！',t:'full',cat:'中文標點'},
    {s:'範圍用 {M}～',                            m:'～',t:'full',cat:'中文標點'},
    {s:'括號內 {M}（說明）',                      m:'（',t:'full',cat:'中文標點'},
    // ─── Python符號（10） ───
    {s:'print{M}"Hello, World!")',                 m:'(', t:'half',cat:'Python符號'},
    {s:'if x {M}= 10:',                              m:'=', t:'half',cat:'Python符號'},
    {s:"name = {M}Andy'",                           m:"'", t:'half',cat:'Python符號'},
    {s:'x = x {M} 1  # 誤用全形運算子',            m:'＋',t:'full',cat:'Python符號'},
    {s:'if True{M}  # 誤用全形冒號',                 m:'：',t:'full',cat:'Python符號'},
    {s:'{M}import numpy as np',                     m:'i', t:'half',cat:'Python符號'},
    {s:'{M}def add(x, y):',                         m:'d', t:'half',cat:'Python符號'},
    {s:'{M}for i in range(10):',                    m:'f', t:'half',cat:'Python符號'},
    {s:'{M}# 這是註解',                             m:'#', t:'half',cat:'Python符號'},
    {s:'{M}class Student:',                         m:'c', t:'half',cat:'Python符號'},
    // ─── 程式碼找錯（20） ───
    {s:'print{M}"Hello"）',                         m:'（',t:'full',cat:'程式碼找錯'},
    {s:'if x {M} 0:',                               m:'＞',t:'full',cat:'程式碼找錯'},
    {s:'x {M} 5',                                   m:'＝',t:'full',cat:'程式碼找錯'},
    {s:'import{M}numpy',                            m:'．',t:'full',cat:'程式碼找錯'},
    {s:'while i {M} 10:',                           m:'<', t:'half',cat:'程式碼找錯'},
    {s:'def hello（）{M}',                           m:'：',t:'full',cat:'程式碼找錯'},
    {s:'name {M}"Andy"',                            m:'＝',t:'full',cat:'程式碼找錯'},
    {s:'print{M}f"Hi {name}"）',                    m:'（',t:'full',cat:'程式碼找錯'},
    {s:'if a{M}= b:',                               m:'！',t:'full',cat:'程式碼找錯'},
    {s:'for i in range{M}10）:',                     m:'（',t:'full',cat:'程式碼找錯'},
    {s:'list{M}append(5)',                          m:'.', t:'half',cat:'程式碼找錯'},
    {s:'len{M}"Hello"）',                           m:'（',t:'full',cat:'程式碼找錯'},
    {s:'x {M} x + 1',                               m:'＝',t:'full',cat:'程式碼找錯'},
    {s:'return{M}x + y）',                          m:'（',t:'full',cat:'程式碼找錯'},
    {s:'{M}print("Hi")`',                           m:'`', t:'half',cat:'程式碼找錯'},
    {s:'str{M}123）',                               m:'（',t:'full',cat:'程式碼找錯'},
    {s:'x >{M} 0  # 大於等於',                      m:'=', t:'half',cat:'程式碼找錯'},
    {s:'try{M}  # 錯誤冒號',                        m:'：',t:'full',cat:'程式碼找錯'},
    {s:'print（"Hello"{M}"World"）',                 m:'，',t:'full',cat:'程式碼找錯'},
    {s:'註解用了 {M}#',                              m:'#', t:'half',cat:'程式碼找錯'},
    {s:'函數結尾多了 {M}）',                         m:'）',t:'full',cat:'程式碼找錯'},
    {s:'全形等號 {M}＝',                              m:'＝',t:'full',cat:'程式碼找錯'},
    {s:'全形加號 {M}＋',                              m:'＋',t:'full',cat:'程式碼找錯'},
];

// ══════════════════════════════════════
// 轉換題題庫（30 題）
// ══════════════════════════════════════
const CONV_POOL=[
    // ─── 半形→全形（單字元 10） ───
    {q:'請將下列字元轉換為【全形】',display:'A', answer:'Ａ', hint:'Shift+空白切換全形，再按 A', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'b', answer:'ｂ', hint:'全形模式後按 b', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'1', answer:'１', hint:'全形模式後按 1', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'Z', answer:'Ｚ', hint:'全形模式 + Shift + z', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'9', answer:'９', hint:'全形模式後按 9', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'!', answer:'！', hint:'全形模式 + Shift + 1', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'?', answer:'？', hint:'全形模式 + Shift + /', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'@', answer:'＠', hint:'全形模式 + Shift + 2', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'(', answer:'（', hint:'全形模式 + Shift + 9', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'.', answer:'．', hint:'全形模式後按 .', cat:'轉換練習'},
    // ─── 全形→半形（單字元 10） ───
    {q:'請將下列字元轉換為【半形】',display:'Ａ', answer:'A', hint:'按空白鍵切回半形再按 A', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'ｂ', answer:'b', hint:'半形模式後按 b', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'１', answer:'1', hint:'半形模式後按 1', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'Ｚ', answer:'Z', hint:'半形模式 + Shift + z', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'９', answer:'9', hint:'半形模式後按 9', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'！', answer:'!', hint:'半形模式 + Shift + 1', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'？', answer:'?', hint:'半形模式 + Shift + /', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'＠', answer:'@', hint:'半形模式 + Shift + 2', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'（', answer:'(', hint:'半形模式 + Shift + 9', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'．', answer:'.', hint:'半形模式後按 .', cat:'轉換練習'},
    // ─── 字串轉換（10） ───
    {q:'請將下列字串轉換為【全形】',display:'Hello', answer:'Ｈｅｌｌｏ', hint:'每個字母都轉全形', cat:'轉換練習'},
    {q:'請將下列字串轉換為【全形】',display:'World', answer:'Ｗｏｒｌｄ', hint:'W 要大寫全形', cat:'轉換練習'},
    {q:'請將下列字串轉換為【全形】',display:'123', answer:'１２３', hint:'全形模式後依序按 123', cat:'轉換練習'},
    {q:'請將下列字串轉換為【半形】',display:'１２３', answer:'123', hint:'半形模式後依序按 123', cat:'轉換練習'},
    {q:'請將下列字串轉換為【半形】',display:'Ｈｉ！', answer:'Hi!', hint:'驚嘆號也要轉半形', cat:'轉換練習'},
    {q:'請將下列字串轉換為【半形】',display:'（測試）', answer:'(測試)', hint:'括號轉半形，中文不變', cat:'轉換練習'},
    {q:'請將下列字串轉換為【全形】',display:'(OK)', answer:'（ＯＫ）', hint:'全部轉全形（含字母）', cat:'轉換練習'},
    {q:'請將下列字串中的全形符號轉半形',display:'你好，世界！', answer:'你好,世界!', hint:'逗號和驚嘆號改半形', cat:'轉換練習'},
    {q:'請將下列字串中的全形符號轉半形',display:'請問？Ａ：是的。', answer:'請問?A:是的。', hint:'問號冒號改半形，句號不變', cat:'轉換練習'},
    {q:'請將下列字串轉換為【半形】',display:'Ｐｙｔｈｏｎ３', answer:'Python3', hint:'全部轉半形', cat:'轉換練習'},
    {q:'請將下列字元轉換為【全形】',display:'*', answer:'＊', hint:'全形模式 + Shift + 8', cat:'轉換練習'},
    {q:'請將下列字元轉換為【半形】',display:'＋', answer:'+', hint:'半形模式 + Shift + =', cat:'轉換練習'},
    {q:'請將下列字串轉換為【全形】',display:'U.S.A.', answer:'Ｕ．Ｓ．Ａ．', hint:'字母和點號都轉全形', cat:'轉換練習'},
    {q:'請將下列字串轉換為【半形】',display:'＋１', answer:'+1', hint:'加號和數字都轉半形', cat:'轉換練習'},
];

// ══════════════════════════════════════
// 輸入題題庫
// ══════════════════════════════════════

// 保底題：雙引號（從此池隨機抽1）
const POOL_DQUOTE=[
    {q:'請輸入 Python 字串（半形雙引號包住）',       preview:'"Hello"',          answer:'"Hello"',          hint:'雙引號 " 為半形（Shift+\'）',       cat:'Python符號'},
    {q:'請輸入 Python print 函數呼叫',               preview:'print("Hi")',       answer:'print("Hi")',       hint:'括號與引號皆為半形',                cat:'Python符號'},
    {q:'請輸入 Python 字串賦值（雙引號）',           preview:'x = "ok"',         answer:'x = "ok"',         hint:'= 引號 空白皆半形',                 cat:'Python符號'},
    {q:'請輸入 Python 雙引號空字串',                 preview:'""',               answer:'""',               hint:'兩個半形雙引號',                    cat:'Python符號'},
    {q:'請輸入 Python 雙引號 f-string',              preview:'f"Hi {name}"',     answer:'f"Hi {name}"',     hint:'f 小寫，引號大括號皆半形',          cat:'Python符號'},
];

// 保底題：單引號（從此池隨機抽1）
const POOL_SQUOTE=[
    {q:"請輸入 Python 字串（半形單引號包住）",       preview:"'Hello'",          answer:"'Hello'",          hint:"單引號 ' 為半形，直接輸入",         cat:'Python符號'},
    {q:"請輸入 Python 單引號字串賦值",               preview:"s = 'ok'",         answer:"s = 'ok'",         hint:"= 和 ' 皆為半形",                  cat:'Python符號'},
    {q:"請輸入 Python 單引號空字串",                 preview:"''",               answer:"''",               hint:"兩個半形單引號",                    cat:'Python符號'},
    {q:"請輸入 Python 單引號 f-string",              preview:"f'Hi {x}'",        answer:"f'Hi {x}'",        hint:"f 小寫，單引號大括號皆半形",        cat:'Python符號'},
    {q:"請輸入 Python 字典（單引號鍵值）",           preview:"{'a': 1}",         answer:"{'a': 1}",         hint:"大括號單引號冒號皆半形",            cat:'Python符號'},
];

// 保底題：\n 換行（固定這一題）
const ITEM_NEWLINE={
    q:'請輸入含換行符號的 Python 字串',
    preview:'"What is your name?\\n"',
    answer:'"What is your name?\\n"',
    hint:'雙引號、?、\\ 和 n 皆為半形',
    cat:'Python符號'
};

// 一般題庫（不含上方保底題）
const POOL_GENERAL=[
    // ─── 半形英文/句子（8） ───
    {q:'請輸入英文問候語（含半形驚嘆號）',           preview:'Hello!',           answer:'Hello!',           hint:'H 大寫，! 為半形 Shift+1',          cat:'抬頭大寫'},
    {q:'請輸入英文完整問候語（含半形逗號與驚嘆號）', preview:'Hello, World!',    answer:'Hello, World!',    hint:'逗號和驚嘆號皆為半形',              cat:'半形符號'},
    {q:'請輸入 Email 地址格式',                      preview:'andy@mail.com',    answer:'andy@mail.com',    hint:'@ 和 . 皆為半形',                   cat:'半形符號'},
    {q:'請輸入英文自我介紹句（含句號）',             preview:'My name is Andy.', answer:'My name is Andy.', hint:'M 和 A 大寫，. 為半形句號',          cat:'抬頭大寫'},
    {q:'請輸入小寫英文單字',                         preview:'world',            answer:'world',            hint:'全部半形小寫',                       cat:'半形英文'},
    {q:'請輸入大寫英文縮寫',                         preview:'USA',              answer:'USA',              hint:'全部半形大寫',                      cat:'抬頭大寫'},
    {q:'請輸入混合大小寫單字',                       preview:'iPhone',           answer:'iPhone',           hint:'i 小寫 P 大寫',                     cat:'半形英文'},
    {q:'請輸入帳號格式',                             preview:'user_001',         answer:'user_001',         hint:'底線和數字皆半形',                  cat:'半形英文'},
    // ─── 全形符號/中文標點（8） ───
    {q:'請輸入含全形逗號的中文片段',                 preview:'你好，世界',        answer:'你好，世界',        hint:'，為全形逗號（中文輸入法）',          cat:'全形符號'},
    {q:'請輸入含全形句號的中文短句',                 preview:'早安。',            answer:'早安。',            hint:'。為全形句號（中文輸入法）',          cat:'中文標點'},
    {q:'請輸入含全形問號的句子',                     preview:'你好嗎？',          answer:'你好嗎？',          hint:'？為全形問號（中文輸入法）',          cat:'全形符號'},
    {q:'請輸入含全形括號的句子',                     preview:'（你好）',          answer:'（你好）',          hint:'（）為全形括號（中文輸入法）',        cat:'中文標點'},
    {q:'請輸入含頓號的列舉',                         preview:'貓、狗、鳥',        answer:'貓、狗、鳥',        hint:'、為頓號（中文輸入法）',              cat:'中文標點'},
    {q:'請輸入含全形驚嘆號的句子',                   preview:'早安！',            answer:'早安！',            hint:'！為全形驚嘆號',                    cat:'全形符號'},
    {q:'請輸入含全形冒號的句子',                     preview:'他說：好的',        answer:'他說：好的',        hint:'：為全形冒號',                      cat:'中文標點'},
    {q:'請輸入含全形驚嘆號的短語',                   preview:'生日快樂！',        answer:'生日快樂！',        hint:'！為全形驚嘆號（中文輸入法）',        cat:'中文標點'},
    // ─── Python 語法（10） ───
    {q:'請輸入 Python 布林值（真）',                 preview:'True',             answer:'True',             hint:'T 大寫，其餘小寫，全半形',           cat:'Python符號'},
    {q:'請輸入 Python 布林值（假）',                 preview:'False',            answer:'False',            hint:'F 大寫，其餘小寫，全半形',           cat:'Python符號'},
    {q:'請輸入 Python 比較運算式',                   preview:'x == 5',           answer:'x == 5',           hint:'== 和空白皆為半形',                 cat:'Python符號'},
    {q:'請輸入 Python 不等於運算式',                 preview:'x != 0',           answer:'x != 0',           hint:'!= 和空白皆為半形',                 cat:'Python符號'},
    {q:'請輸入 Python 清單',                         preview:'[1, 2, 3]',        answer:'[1, 2, 3]',        hint:'方括號逗號皆為半形',                cat:'Python符號'},
    {q:'請輸入 Python 條件句開頭',                   preview:'if x > 0:',        answer:'if x > 0:',        hint:'> 和 : 皆為半形',                  cat:'Python符號'},
    {q:'請輸入 Python 加法運算式',                   preview:'a + b',            answer:'a + b',            hint:'+ 和空白皆為半形',                  cat:'Python符號'},
    {q:'請輸入 Python 註解',                         preview:'# 這是註解',        answer:'# 這是註解',        hint:'# 為半形，空白為半形',              cat:'Python符號'},
    {q:'請輸入 Python 索引取值',                     preview:'list[0]',          answer:'list[0]',          hint:'方括號數字皆半形',                  cat:'Python符號'},
    {q:"請輸入 Python 換行字串（單引號）",           preview:"'\\n'",            answer:"'\\n'",            hint:"單引號與反斜線皆為半形",             cat:'Python符號'},
    {q:'請輸入 Python 列表推導式',                   preview:'[x*2 for x]',      answer:'[x*2 for x]',      hint:'全部半形字元',                      cat:'Python符號'},
    {q:'請輸入 Python 字典',                         preview:'{"a": 1}',          answer:'{"a": 1}',          hint:'大括號冒號逗號皆半形',              cat:'Python符號'},
    // ─── 半形數字（7） ───
    {q:'請輸入半形數字（座號格式）',                  preview:'12',               answer:'12',               hint:'直接輸入數字鍵',                    cat:'半形數字'},
    {q:'請輸入半形電話號碼格式',                      preview:'0912',             answer:'0912',             hint:'數字鍵直接輸入',                    cat:'半形數字'},
    {q:'請輸入半形數字 0 到 4',                       preview:'01234',            answer:'01234',            hint:'數字鍵依序輸入',                    cat:'半形數字'},
    {q:'請輸入常見 port 號',                          preview:'8080',             answer:'8080',             hint:'數字鍵輸入',                        cat:'半形數字'},
    {q:'請輸入半形年份',                              preview:'2024',             answer:'2024',             hint:'數字鍵輸入四位數',                  cat:'半形數字'},
    {q:'請輸入半形 IP 位址',                          preview:'192.168.1.1',      answer:'192.168.1.1',      hint:'點號也是半形',                     cat:'半形數字'},
    {q:'請輸入半形版本號',                            preview:'v2.0.1',           answer:'v2.0.1',           hint:'v 小寫，點號數字皆半形',            cat:'半形數字'},
    // ─── 全形數字（7） ───
    {q:'請輸入全形數字一到五',                        preview:'１２３４５',        answer:'１２３４５',        hint:'全形模式後按 1-5',                  cat:'全形數字'},
    {q:'請輸入全形座號',                              preview:'１２',             answer:'１２',             hint:'全形模式後按 1 和 2',              cat:'全形數字'},
    {q:'請輸入全形數字 ０',                           preview:'０',               answer:'０',               hint:'全形模式後按 0',                    cat:'全形數字'},
    {q:'請輸入全形金額',                              preview:'５００',            answer:'５００',            hint:'全形模式後按 5、0、0',              cat:'全形數字'},
    {q:'請輸入全形年份',                              preview:'２０２４',          answer:'２０２４',          hint:'全形模式後輸入 2024',               cat:'全形數字'},
    {q:'請輸入全形溫度',                              preview:'２８度C',            answer:'２８度C',            hint:'全形模式按 28，度C 為半形',          cat:'全形數字'},
    {q:'請輸入全形房間號碼',                          preview:'１０１',            answer:'１０１',            hint:'全形模式按 101',                    cat:'全形數字'},
    // ─── 全形英文（7） ───
    {q:'請輸入全形大寫英文字母 Ａ',                   preview:'Ａ',               answer:'Ａ',               hint:'全形模式 + Shift + a',              cat:'全形英文'},
    {q:'請輸入全形小寫字母 ｓ',                       preview:'ｓ',               answer:'ｓ',               hint:'全形模式後按 s',                    cat:'全形英文'},
    {q:'請輸入全形大寫 Ｗ',                           preview:'Ｗ',               answer:'Ｗ',               hint:'全形模式 + Shift + w',              cat:'全形英文'},
    {q:'請輸入全形小寫 ｍ',                           preview:'ｍ',               answer:'ｍ',               hint:'全形模式後按 m',                    cat:'全形英文'},
    {q:'請輸入全形大寫 Ｚ',                           preview:'Ｚ',               answer:'Ｚ',               hint:'全形模式 + Shift + z',              cat:'全形英文'},
    {q:'請輸入全形小寫 ｘ',                           preview:'ｘ',               answer:'ｘ',               hint:'全形模式後按 x',                    cat:'全形英文'},
    {q:'請輸入全形大寫 Hello',                        preview:'Ｈｅｌｌｏ',        answer:'Ｈｅｌｌｏ',        hint:'依序全形輸入 H e l l o',            cat:'全形英文'},
    // ─── 程式碼改錯（20） ───
    {q:'修正以下程式碼的全形/半形錯誤',               preview:'print（"Hello"）',       answer:'print("Hello")',       hint:'括號和引號必須是半形',              cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'x ＝ 5',                answer:'x = 5',                hint:'等號應為半形',                     cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'if y ＜ 5：',            answer:'if y < 5:',            hint:'小於和冒號改半形',                 cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'name = input（"姓名"）',  answer:'name = input("姓名")',   hint:'括號引號改半形',                   cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'print（f"Hi，{name}"）',  answer:'print(f"Hi,{name}")',    hint:'括號和逗號改半形',                 cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'for i in range（10）：',    answer:'for i in range(10):',    hint:'括號冒號改半形',                   cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'if a ！= b：',             answer:'if a != b:',            hint:'驚嘆號和冒號改半形',               cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'import．numpy',            answer:'import numpy',            hint:'點號改空白',                       cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'x ＝ x ＋ 1',              answer:'x = x + 1',              hint:'等號和加號改半形',                 cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'def hello（):',            answer:'def hello():',            hint:'括號改半形，移除全形括號',         cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'while i ＞ 0：',            answer:'while i > 0:',            hint:'大於和冒號改半形',                 cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'name ＝ "Hello"',          answer:'name = "Hello"',          hint:'等號改半形',                       cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'x = y ？ 1 ： 0',           answer:'x = y ? 1 : 0',            hint:'問號冒號改半形',                   cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'str（123）',                answer:'str(123)',                hint:'括號改半形',                       cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'int（"100"）',              answer:'int("100")',              hint:'括號引號改半形',                   cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'len（"Hi"）',               answer:'len("Hi")',               hint:'括號引號改半形',                   cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'a ＆ b',                    answer:'a & b',                    hint:'＆改半形 &',                       cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'if True：',                  answer:'if True:',                  hint:'冒號改半形',                       cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'return（x＋y）',             answer:'return x + y',              hint:'移除全形括號，加號改半形',         cat:'程式碼找錯'},
    {q:'修正以下程式碼的全形/半形錯誤',                preview:'print（Hello，World！）',    answer:'print("Hello, World!")',    hint:'全部改半形並加引號',               cat:'程式碼找錯'},
    {q:'請輸入英文問句（含問號）',                     preview:'How are you?',    answer:'How are you?',    hint:'H 大寫，? 為半形',                  cat:'半形符號'},
    {q:'請輸入全形括號句子',                           preview:'今天（星期一）',  answer:'今天（星期一）',  hint:'（）為全形括號',                     cat:'中文標點'},
    {q:'請輸入 Python 減法',                           preview:'x - y',          answer:'x - y',          hint:'減號和空白皆半形',                   cat:'Python符號'},
    {q:'請輸入半形郵遞區號',                           preview:'100',            answer:'100',            hint:'數字鍵輸入三位數',                   cat:'半形數字'},
    {q:'請輸入全形數字六到十',                         preview:'６７８９０',     answer:'６７８９０',     hint:'全形模式按 6-0',                     cat:'全形數字'},
    {q:'修正全形錯誤',                                 preview:'print（"OK"）',  answer:'print("OK")',    hint:'括號改半形',                         cat:'程式碼找錯'},
    {q:'請輸入 Python 大於等於',                       preview:'x >= 5',         answer:'x >= 5',         hint:'>= 皆為半形',                       cat:'Python符號'},
];

// ══════════════════════════════════════
// 程式修復題庫（15 題，全形半形皆左右對稱）
// ══════════════════════════════════════
const REPAIR_POOL=[
    // 2 個錯誤（5）
    {q:'修正以下程式碼（2 個錯誤）',display:'print（"Hello"）',     answer:'print("Hello")',     errCount:2, hint:'全形括號（）改半形()',   cat:'程式碼修復'},
    {q:'修正以下程式碼（2 個錯誤）',display:'if x ＞ 0：',            answer:'if x > 0:',          errCount:2, hint:'＞改>，：改:',             cat:'程式碼修復'},
    {q:'修正以下程式碼（2 個錯誤）',display:'def add（a, b）',        answer:'def add(a, b)',      errCount:2, hint:'全形括號（）改半形()',   cat:'程式碼修復'},
    {q:'修正以下程式碼（2 個錯誤）',display:'str（"Hi"）',            answer:'str("Hi")',          errCount:2, hint:'全形括號（）改半形()',   cat:'程式碼修復'},
    {q:'修正以下程式碼（2 個錯誤）',display:'while y ＜ 0：',          answer:'while y < 0:',       errCount:2, hint:'＜改<，：改:',             cat:'程式碼修復'},
    // 3 個錯誤（5）
    {q:'修正以下程式碼（3 個錯誤）',display:'for i in range（10）：',   answer:'for i in range(10):', errCount:3, hint:'（ ） ：皆改半形',       cat:'程式碼修復'},
    {q:'修正以下程式碼（3 個錯誤）',display:'x ＝ x ＋ 1；',           answer:'x = x + 1;',         errCount:3, hint:'＝改=，＋改+，；改;',   cat:'程式碼修復'},
    {q:'修正以下程式碼（3 個錯誤）',display:'name ＝ input（"Name"）',  answer:'name = input("Name")',errCount:3, hint:'＝改=，全形括號改半形',    cat:'程式碼修復'},
    {q:'修正以下程式碼（3 個錯誤）',display:'print（"Hello，World"）',  answer:'print("Hello,World")',errCount:3, hint:'（ ） ，皆改半形',     cat:'程式碼修復'},
    {q:'修正以下程式碼（3 個錯誤）',display:'if a ！= 0：',            answer:'if a != 0:',         errCount:3, hint:'！改!，：改:',             cat:'程式碼修復'},
    // 4 個錯誤（5）
    {q:'修正以下程式碼（4 個錯誤）',display:'print（「Hello」）',     answer:'print("Hello")',     errCount:4, hint:'（）「」皆改半形',        cat:'程式碼修復'},
    {q:'修正以下程式碼（4 個錯誤）',display:'str（"１２３"）',         answer:'str("123")',         errCount:4, hint:'括號及全形數字改半形',   cat:'程式碼修復'},
    {q:'修正以下程式碼（4 個錯誤）',display:'print（f"Hi，{name}"）',  answer:'print(f"Hi,{name}")', errCount:4, hint:'（ ） ，皆改半形',     cat:'程式碼修復'},
    {q:'修正以下程式碼（4 個錯誤）',display:'x ＝ int（"５"）',        answer:'x = int("5")',       errCount:4, hint:'＝（ ）５改半形',        cat:'程式碼修復'},
    {q:'修正以下程式碼（4 個錯誤）',display:'print（"Hello，World！"）', answer:'print("Hello,World!")',errCount:4, hint:'（），，！改半形',cat:'程式碼修復'},
];
